### ISSUE TITLE
some function's method type is wrong

### ISSUE THREAD

**Issue by Hellager** [knisshoku/pvea#15]
functions (getLxcPending, getLxcConfig, getLxcRRDData, getLxcContainersStatus) have such a problem, their method type should be GET not POST.

**Comment by kurusukono** [comment]
Hello! I'll fix the issues by next Wednesday. Thank you!

**Comment by knisshoku** [comment]
Apologies about the delays. I've since resolved this in commit https://github.com/knisshoku/pvea/commit/34e1ca43e8ca11568b6323fc0b78d47fbfb0a5d9

getLxcRRDData() and getLxcContainerStatus() were already get requests.

**Comment by Hellager** [comment]
Thanks for your greate job. It works well  : )
